name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04 # Especificar la versión de Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Cambia según tu versión de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # Aquí se especifica el comando correctamente

      - name: Build project
        run: npm run build
